version: '3'

services:
  nginx:
    container_name: nginx-${ENV}
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - ${EXTERNAL_PORT_LOCAL1}:${INTERNAL_PORT_LOCAL1}
    volumes:
      - ${SRC_PATH_LOCAL1}:/src
      - ./nginx/def.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    depends_on:
      - php
    command: nginx -g "daemon off;"

# TODO supervisor start on build problem
  php:
    container_name: php-${ENV}
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
        - ${SRC_PATH_LOCAL1}:/src
        - ./php/conf:/usr/local/etc/php/conf.d/custom.ini
        - ./supervisor/supervisord.conf:/etc/supervisor/conf.d/commands.conf

  rabbit:
    container_name: rabbit-${ENV}
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 15672:15672

  db:
    container_name: db-${ENV}
    image: mysql:latest
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: example

  clickhouse:
    container_name: clickhouse-${ENV}
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./clickhouse/data:/var/lib/clickhouse
      - ./clickhouse/log:/var/log/clickhouse-server
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
    depends_on:
      - db
    restart: always

  adminer:
    image: adminer
    ports:
      - 8083:8080
    depends_on:
      - db